# Generated by Django 3.2.5 on 2023-01-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_promocao',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
