# Generated by Django 3.2.5 on 2023-01-18 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0002_produto_preco_promocao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='preco_promocao',
        ),
    ]
