# Generated by Django 3.2.5 on 2023-01-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0003_remove_produto_preco_promocao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='promocao_preco_antigo',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
